os: linux
dist: xenial
language: node_js
node_js:
  - 12.13.0
script:
  - npm run lint
  - npm run test:coveralls
notifications:
  email: false
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key:
    secure: $NPM_ENCRYPTED_KEY
  on:
    tags: true
    repo: stopyransky/fh-hooks
