os: linux
dist: xenial
language: node_js
node_js:
  - 12.13.0
script:
  - npm run lint
  - npm run test:coveralls
notifications:
  email: false
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key:
    secure: IUByRsNy5+ImuZlukoSjlTXXJM77i0Nr48kzriuKhni9G/71FhOFS7YVOSIO3Aewtj0pragENnszN4ZQDmmA2mW7yPbTyPDrIeECioITgC8DU9FuEUHLqnRYVg3nZZc2wohkMaNN91cBrfzI2XJ+Ftsj4wROHhkcMciOgPVzI0qD6Ea8vhBOBdMeLPItqnRxboes8EQXyR9ZwCgWDd/3qq90B35Kj8TvKMYo6ww8vvRncpbGwgG8v/+/ZWzrkWzRfo1BMSjWAAgs/zWlOZfd0RdyImoMic8CHqSPFpv3bkuFmGRknvTgDKVPSakUZGt71cLn6ZhULddjIMLNw84cjko2AFgMEvxFRz6VnVE3o1fzcRc/o5g8UHMpqBf2PzYFm/YOXs+Oou1kHDo4yZauNZjnce0NwHj6QotU9GeBff5JL8BL7vW3cLQDj7Z1LwtSlFR76mJXthg+cWYiN9FR+oXYdq2VAgU+ipgRX1cATitU1/lw0GKh3HQjKlKyPmGZv5f+BEfMnUNCJ+Lgws+Cyth14q/65RLnadg4i6nFmwOnMEgjDTN47yx+2iLtooO9N5OcWB1gKTBBaqhxAITGYuOZa8By4bCLr08SyB5W18GMITvarAUuRjFgbwyrTyHBFRFCqVoSkGAWYPd4zsNvWthu3ow7m4bXrn5eIb6/dHc=
  on:
    tags: true
    repo: stopyransky/fh-hooks
