os: linux
dist: xenial
language: node_js
node_js:
  - 12.13.0
script:
  - npm run lint
  - npm run test:coveralls
deploy:
  provider: npm
  email: stopyransky@gmail.com
  api_key:
    secure: StwGICP/6+cb3uglW5UVJ5RV8gF55KckyfVd3ASBoZAMemXIjsc34MNHpAfaIG2pq4k8fXSsc8iRpNI2G7piVuvrF6hYl3oAzH+7txACRltwXVQgzt1XzPcuYX7wXOAjEvZrtCff2ASnN1U02hCeWDsmS16/DCP51oz720lth4CC9UGPR4E03nYJJr6DhOEN7IOXb7+ECPlixN5vYlNpMsZGtFn09si5Setg9kF9S2Jw2HC6jyvjFIsHNfYSo+eSkjsjqxmJJ+/CsJKYm9kksx2Zh9YR1plWZnqyHqc8QhjdziN2ELgfUj30OeV5BWLsHhX034OZZJ5D7s+sJTyBhuwdOCuVhlXRLmaQ+hfe7QVHx14a/VQgkXVdO4oQPcaqXR4mpZzhzAhM0W7fdBVkvkQdmOI1IYFoA94vjYqryBCbBgpO1tv9Bad9xvKcK3gWaERK8PexBlBMCzRGEjji8gwhm+mhCxwczBGUnBVuG5ZwrGObuaGl8fzvtEIcvkZ4WH1qI7SRbed2nBoATfgYMJ7/muyM/Tu5AUhuLYs3MwHope2NMxHv4WSQbcoD9edtJilqYxVbNtiASfMxLAQhM+ozC1OmRXDivLPGnG3GpDzymYB8M67defIzIB6jJpzwWwLKGSBkrO+7sQG1yW8JpQr9u0nicY2RwSvGWpG0ax0=
  on:
    tags: true
    repo: stopyransky/fh-hooks
notifications:
  email: false
